controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        os_js_routing:
            resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"
    type: attribute
